### ISSUE TITLE
verify / synchronize constants across vlui and polestar/voyager

### ISSUE THREAD

**Issue by kanitw** [uwdata/vega-lite-ui#14]
Currently all three project has lines in `index.js` setting `consts`, which might lead to inconsistency. 

```
.constant('consts', {
…
}
```

**Comment by domoritz** [comment]
Can we just move everything to vl-ui? Sounds crazy but is probably the easiest and cleanest approach.

**Comment by kanitw** [comment]
Yes, that's the plan.  But there must be some overriding mechanism.   For example, project names should be overridden in both project.

**Comment by kanitw** [comment]
fixed in latest PR for both voyager, polestar using `.config()` to override `consts`
